### ISSUE TITLE
Not Sync

### ISSUE THREAD

**Issue by whizsid** [stevepryde/thirtyfour_query#1] opened 2020-11-20 21:06 UTC
Can not use in multi threaded programs. Because all of these async blocks are not `Sync`

**Comment by stevepryde** [comment] 2020-11-22 06:10
Can you please provide more detail on what you are trying to do?

**Comment by fapingalot** [comment] 2020-12-04 13:32
I also have this problem
```
error: future cannot be sent between threads safely
    --> src/modules/quest.rs:43:27
     |
43   |       ) -> Result<Home<'a>> {
     |  ___________________________^
44   | |         // Handle items for fight
45   | |         if manager.quest_got_item {
46   | |             manager.quest_got_item = false;
...    |
93   | |         Ok(home)
94   | |     }
     | |_____^ future returned by `__execute` is not `Send`
     |
     = help: the trait `std::marker::Send` is not implemented for `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn futures::Future<Output = bool> + 'a)>> + 'static)`
note: future is not `Send` as this value is used across an await
    --> src/lib.rs:3226:15
     |
3226 | ...   match c.query(By::Css(r#"#controls > [rel="next"][style*="display: inline-block;"][act="end_play"], #controls > [rel="next"][style*="display: inline-block;"][act="free"]"#)).first().awai...
     |             -----------------------------------------------------------------------------------------------------------------------------------------------------------------------^^^^^^^^^^^^^^
     |             |
     |             await occurs here, with `c.query(By::Css(r#"#controls > [rel="next"][style*="display: inline-block;"][act="end_play"], #controls > [rel="next"][style*="display: inline-block;"][act="free"]"#))` maybe used later
     |             has type `ElementQuery<'_>` which is not `Send`
...
3230 | ...   }
     |       - `c.query(By::Css(r#"#controls > [rel="next"][style*="display: inline-block;"][act="end_play"], #controls > [rel="next"][style*="display: inline-block;"][act="free"]"#))` is later dropped here
help: consider moving this into a `let` binding to create a shorter lived borrow
    --> src/lib.rs:3226:15
     |
3226 | ...ch c.query(By::Css(r#"#controls > [rel="next"][style*="display: inline-block;"][act="end_play"], #controls > [rel="next"][style*="display: inline-block;"][act="free"]"#)).first().aw...
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: required for the cast to the object type `dyn futures::Future<Output = std::result::Result<Home<'a>, anyhow::Error>> + std::marker::Send`


```

**Comment by audioXD** [comment] 2020-12-04 13:51
This is the smallest example I could find

```
use thirtyfour::prelude::*;
use thirtyfour_query::*;

pub fn is_send<T: Send>(t: T) {}

#[tokio::main]
async fn main() -> WebDriverResult<()> {
    let caps = DesiredCapabilities::chrome();
    let driver = WebDriver::new("http://localhost:4444/wd/hub", &caps).await?;

    is_send(driver.query(By::Css("body")).first());

    Ok(())
}
```

The Error is
```
error[E0277]: `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)` cannot be shared between threads safely
  --> src/main.rs:11:5
   |
4  | pub fn is_send<T: Send>(t: T) {}
   |                   ---- required by this bound in `is_send`
...
11 |     is_send(driver.query(By::Css("body")).first());
   |     ^^^^^^^ `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)`
   = note: required because of the requirements on the impl of `Sync` for `Unique<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>`
   = note: required because it appears within the type `Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>`
   = note: required because of the requirements on the impl of `Sync` for `Unique<Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>>`
   = note: required because it appears within the type `Vec<Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>>`
   = note: required because it appears within the type `ElementSelector<'_>`
   = note: required because of the requirements on the impl of `Sync` for `Unique<ElementSelector<'_>>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<ElementSelector<'_>>`
   = note: required because it appears within the type `Vec<ElementSelector<'_>>`
   = note: required because it appears within the type `ElementQuery<'_>`
   = note: required because of the requirements on the impl of `Send` for `&ElementQuery<'_>`
   = note: required because it appears within the type `[static generator@ElementQuery::<'a>::first::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementQuery::<'a>::first::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`

error[E0277]: `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)` cannot be sent between threads safely
  --> src/main.rs:11:5
   |
4  | pub fn is_send<T: Send>(t: T) {}
   |                   ---- required by this bound in `is_send`
...
11 |     is_send(driver.query(By::Css("body")).first());
   |     ^^^^^^^ `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)` cannot be sent between threads safely
   |
   = help: the trait `Send` is not implemented for `(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)`
   = note: required because of the requirements on the impl of `Send` for `Unique<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>`
   = note: required because it appears within the type `Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>`
   = note: required because of the requirements on the impl of `Send` for `Unique<Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>>`
   = note: required because it appears within the type `Vec<Box<(dyn for<'a> Fn(&'a thirtyfour::WebElement<'a>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 'a)>> + 'static)>>`
   = note: required because it appears within the type `ElementSelector<'_>`
   = note: required because of the requirements on the impl of `Send` for `Unique<ElementSelector<'_>>`
   = note: required because it appears within the type `alloc::raw_vec::RawVec<ElementSelector<'_>>`
   = note: required because it appears within the type `Vec<ElementSelector<'_>>`
   = note: required because it appears within the type `ElementQuery<'_>`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3> {ResumeTy, &'r ElementQuery<'s>, ElementQuery<'t0>, ElementPoller, Option<Duration>, u32, impl std::future::Future, (), Duration}`
   = note: required because it appears within the type `[static generator@ElementQuery::<'a>::run_poller::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3> {ResumeTy, &'r ElementQuery<'s>, ElementQuery<'t0>, ElementPoller, Option<Duration>, u32, impl std::future::Future, (), Duration}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementQuery::<'a>::run_poller::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3> {ResumeTy, &'r ElementQuery<'s>, ElementQuery<'t0>, ElementPoller, Option<Duration>, u32, impl std::future::Future, (), Duration}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}`
   = note: required because it appears within the type `[static generator@ElementQuery::<'a>::first::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementQuery::<'a>::first::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`

error[E0277]: `dyn std::future::Future<Output = bool>` cannot be sent between threads safely
  --> src/main.rs:11:5
   |
4  | pub fn is_send<T: Send>(t: T) {}
   |                   ---- required by this bound in `is_send`
...
11 |     is_send(driver.query(By::Css("body")).first());
   |     ^^^^^^^ `dyn std::future::Future<Output = bool>` cannot be sent between threads safely
   |
   = help: the trait `Send` is not implemented for `dyn std::future::Future<Output = bool>`
   = note: required because of the requirements on the impl of `Send` for `Unique<dyn std::future::Future<Output = bool>>`
   = note: required because it appears within the type `Box<dyn std::future::Future<Output = bool>>`
   = note: required because it appears within the type `Pin<Box<dyn std::future::Future<Output = bool>>>`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13> {ResumeTy, &'r ElementSelector<'s>, Vec<thirtyfour::WebElement<'t0>>, ElementSelector<'t1>, Vec<Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't2)>>, &'t3 Vec<Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't4)>>, std::slice::Iter<'t5, Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't6)>>, &'t7 Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't8)>, std::vec::IntoIter<thirtyfour::WebElement<'t9>>, thirtyfour::WebElement<'t10>, &'t11 thirtyfour::WebElement<'t12>, Pin<Box<(dyn std::future::Future<Output = bool> + 't13)>>, ()}`
   = note: required because it appears within the type `[static generator@ElementSelector::<'a>::run_filters::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13> {ResumeTy, &'r ElementSelector<'s>, Vec<thirtyfour::WebElement<'t0>>, ElementSelector<'t1>, Vec<Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't2)>>, &'t3 Vec<Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't4)>>, std::slice::Iter<'t5, Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't6)>>, &'t7 Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't8)>, std::vec::IntoIter<thirtyfour::WebElement<'t9>>, thirtyfour::WebElement<'t10>, &'t11 thirtyfour::WebElement<'t12>, Pin<Box<(dyn std::future::Future<Output = bool> + 't13)>>, ()}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementSelector::<'a>::run_filters::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13> {ResumeTy, &'r ElementSelector<'s>, Vec<thirtyfour::WebElement<'t0>>, ElementSelector<'t1>, Vec<Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't2)>>, &'t3 Vec<Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't4)>>, std::slice::Iter<'t5, Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't6)>>, &'t7 Box<(dyn for<'t14> Fn(&'t14 thirtyfour::WebElement<'t14>) -> Pin<Box<(dyn std::future::Future<Output = bool> + 't14)>> + 't8)>, std::vec::IntoIter<thirtyfour::WebElement<'t9>>, thirtyfour::WebElement<'t10>, &'t11 thirtyfour::WebElement<'t12>, Pin<Box<(dyn std::future::Future<Output = bool> + 't13)>>, ()}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16> {ResumeTy, &'r ElementQuery<'s>, Option<Duration>, u32, WebDriverError, tokio::time::Instant, ElementQuery<'t0>, Vec<ElementSelector<'t1>>, &'t2 Vec<ElementSelector<'t3>>, std::slice::Iter<'t4, ElementSelector<'t5>>, &'t6 ElementSelector<'t7>, impl std::future::Future, (), Vec<thirtyfour::WebElement<'t12>>, bool, impl std::future::Future, Duration, Delay}`
   = note: required because it appears within the type `[static generator@ElementQuery::<'a>::run_poller_with_options::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16> {ResumeTy, &'r ElementQuery<'s>, Option<Duration>, u32, WebDriverError, tokio::time::Instant, ElementQuery<'t0>, Vec<ElementSelector<'t1>>, &'t2 Vec<ElementSelector<'t3>>, std::slice::Iter<'t4, ElementSelector<'t5>>, &'t6 ElementSelector<'t7>, impl std::future::Future, (), Vec<thirtyfour::WebElement<'t12>>, bool, impl std::future::Future, Duration, Delay}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementQuery::<'a>::run_poller_with_options::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6, 't7, 't8, 't9, 't10, 't11, 't12, 't13, 't14, 't15, 't16> {ResumeTy, &'r ElementQuery<'s>, Option<Duration>, u32, WebDriverError, tokio::time::Instant, ElementQuery<'t0>, Vec<ElementSelector<'t1>>, &'t2 Vec<ElementSelector<'t3>>, std::slice::Iter<'t4, ElementSelector<'t5>>, &'t6 ElementSelector<'t7>, impl std::future::Future, (), Vec<thirtyfour::WebElement<'t12>>, bool, impl std::future::Future, Duration, Delay}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2, 't3> {ResumeTy, &'r ElementQuery<'s>, ElementQuery<'t0>, ElementPoller, Option<Duration>, u32, impl std::future::Future, (), Duration}`
   = note: required because it appears within the type `[static generator@ElementQuery::<'a>::run_poller::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3> {ResumeTy, &'r ElementQuery<'s>, ElementQuery<'t0>, ElementPoller, Option<Duration>, u32, impl std::future::Future, (), Duration}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementQuery::<'a>::run_poller::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3> {ResumeTy, &'r ElementQuery<'s>, ElementQuery<'t0>, ElementPoller, Option<Duration>, u32, impl std::future::Future, (), Duration}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}`
   = note: required because it appears within the type `[static generator@ElementQuery::<'a>::first::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}]`
   = note: required because it appears within the type `from_generator::GenFuture<[static generator@ElementQuery::<'a>::first::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r ElementQuery<'s>, impl std::future::Future, ()}]>`
   = note: required because it appears within the type `impl std::future::Future`
   = note: required because it appears within the type `impl std::future::Future`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `wd-error`

To learn more, run the command again with --verbose.
```

**Comment by stevepryde** [comment] 2020-12-04 21:31
I guess my question is why do you want to control a single browser session from multiple threads? Surely this will be prone to races because the order in which you execute commands on the browser will be critically important.

I haven't tried yet but is it possible to just wrap the WebDriver in a mutex?

**Comment by audioXD** [comment] 2020-12-04 21:36
I don't specifically want it but when i try using it in a [async_trait](https://docs.rs/async-trait/0.1.7/async_trait/) it requires it to be `Sync`.I don't know the specifics why it has to be `Sync`.

**Comment by stevepryde** [comment] 2020-12-04 21:41
Ok that makes more sense then. I'll have a look into it. Thanks 👍

**Comment by stevepryde** [comment] 2020-12-05 12:46
I've narrowed it down. The problem is with the closures (filters) being stored in `ElementSelector`. Given that these are not needed in most cases, I'm going to split them out and create a "lighter" `ElementQuery` without any filtering.

I'll probably keep the filtering functions in a separate branch but remove them from the main crate for now, until I can come up with a solution for this. :(

**Comment by stevepryde** [comment] 2020-12-05 23:51
@audioXD Is this one fixed by https://github.com/stevepryde/thirtyfour_query/pull/2 as well?

**Comment by audioXD** [comment] 2020-12-05 23:51
It is

**Comment by stevepryde** [comment] 2020-12-05 23:51
Ok, closing this one as well. Fixed by https://github.com/stevepryde/thirtyfour_query/pull/2

**Closed as completed by stevepryde** 2020-12-05 23:51 UTC
